### ISSUE TITLE
What typeface are you using in the theme?

### ISSUE THREAD

**Issue by Kaske** [dracula/mindnode#1]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

**Comment by zenorocha** [comment]
Good question, I don't quite remember and I don't have that file with me anymore :/

Sorry about that

**Comment by eivindml** [comment]
Why close issue just because you can't answer it? 

It's the San Fransisco Mono font by Apple. [How to get it](https://medium.com/@shashikant.jagtap/getting-apples-sf-mono-font-in-macos-1de5183add84).

**Comment by zenorocha** [comment]
Thanks @eivindml!
